version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=arquitectura_db
      - DB_USERNAME=root
      - DB_PASSWORD=root

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=arquitectura_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
